from . import settings_whatsapp
from . import sincpro_whatsapp
from . import inherit_account_move_form
from . import inherit_sale_order
from . import inherit_crm_lead
from . import inherit_res_partner
from . import data_processor
from . import messenger_message
from . import social_media_messages
